# -*- coding: utf-8 -*-
"""ALDEP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vQZWNTNxBkJ2UahmKBbgEyXqEJ2RB8qc
"""

import random
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
import numpy as np

class ALDEP:
    def __init__(self, departments, areas, rel_matrix, facility_width):

        self.departments = departments
        self.areas = areas
        self.rel_matrix = rel_matrix
        self.facility_width = facility_width

        # ALDEP relationship scores
        self.scores = {'A': 64, 'E': 16, 'I': 4, 'O': 1, 'U': 0, 'X': -1024}

        # Calculate facility height
        total_area = sum(areas.values())
        self.facility_height = int(np.ceil(total_area / facility_width))
        self.grid = np.full((self.facility_height, self.facility_width), None)

    def _get_rel_score(self, dept1, dept2):
        idx1 = self.departments.index(dept1)
        idx2 = self.departments.index(dept2)
        return self.scores[self.rel_matrix[idx1][idx2]]

    import random

    def generate_sequence(self, mdp_letter):

        mdp_score = self.scores[mdp_letter]

        unplaced = self.departments.copy()
        sequence = []

        # Select a department randomly and place in the layout
        current = random.choice(unplaced)
        sequence.append(current)
        unplaced.remove(current)


        while unplaced:
            list_a = []
            list_b = []

            # Classify the unselected departments into List A and List B
            for candidate in unplaced:
                score = self._get_rel_score(current, candidate)

                if score < mdp_score:
                    list_a.append(candidate) # Less than MDP value
                else:
                    list_b.append(candidate) # Greater than or equal to MDP value

            # Select the next department to place
            if not list_b:
                # If List B is empty, select a department randomly from List A
                best_next = random.choice(list_a)
            else:
                # Otherwise, select the department from List B with the maximum REL value
                best_next = None
                best_score = -float('inf')

                for candidate in list_b:
                    score = self._get_rel_score(current, candidate)
                    if score > best_score:
                        best_score = score
                        best_next = candidate


            # Place the chosen department and update the current tracker
            sequence.append(best_next)
            unplaced.remove(best_next)
            current = best_next

        return sequence

    def place_departments(self, sequence):
        x, y = 0, 0
        direction = 1 # 1 for down, -1 for up

        for dept in sequence:
            blocks_needed = self.areas[dept]

            while blocks_needed > 0:
                self.grid[y][x] = dept
                blocks_needed -= 1

                # Move to next cell
                y += direction

                # Check boundaries for the sweep pattern
                if y >= self.facility_height or y < 0:
                    direction *= -1 # Reverse direction
                    y += direction  # Step back inside bounds
                    x += 1          # Move to the next column

                    if x >= self.facility_width:
                        break # Facility is full

    def calculate_layout_score(self):
        total_score = 0
        adjacencies = set()

        # Scan the grid for adjacent pairs (horizontal and vertical)
        for y in range(self.facility_height):
            for x in range(self.facility_width):
                current_dept = self.grid[y][x]
                if not current_dept: continue

                # Check Right
                if x + 1 < self.facility_width and self.grid[y][x+1]:
                    neighbor = self.grid[y][x+1]
                    if current_dept != neighbor:
                        pair = tuple(sorted((current_dept, neighbor)))
                        adjacencies.add(pair)

                # Check Down
                if y + 1 < self.facility_height and self.grid[y+1][x]:
                    neighbor = self.grid[y+1][x]
                    if current_dept != neighbor:
                        pair = tuple(sorted((current_dept, neighbor)))
                        adjacencies.add(pair)

        # Sum the scores of unique adjacent pairs
        for dept1, dept2 in adjacencies:
            total_score += self._get_rel_score(dept1, dept2)

        return total_score

    def plot_layout(self, score):
        """Visualizes the grid."""
        fig, ax = plt.subplots(figsize=(6, 6))

        # Create a color map for departments
        colors = list(mcolors.TABLEAU_COLORS.values())
        color_map = {dept: colors[i % len(colors)] for i, dept in enumerate(self.departments)}

        for y in range(self.facility_height):
            for x in range(self.facility_width):
                dept = self.grid[y][x]
                if dept:
                    ax.add_patch(plt.Rectangle((x, self.facility_height - y - 1), 1, 1,
                                               facecolor=color_map[dept], edgecolor='black'))
                    ax.text(x + 0.5, self.facility_height - y - 0.5, dept,
                            color='white', weight='bold', ha='center', va='center')

        plt.xlim(0, self.facility_width)
        plt.ylim(0, self.facility_height)
        plt.xticks(range(self.facility_width + 1))
        plt.yticks(range(self.facility_height + 1))
        plt.title(f"ALDEP Layout (Total Score: {score})")
        plt.grid(True)
        plt.show()

# Example Usage

if __name__ == "__main__":
    # Define the Departments and their required Area
    departments = ['Receiving', 'Milling', 'Press', 'Assembly', 'Shipping']
    areas = {
        'Receiving': 4,
        'Milling': 6,
        'Press': 8,
        'Assembly': 6,
        'Shipping': 4
    }

    # Define the AEIOUX Relationship Matrix
    rel_matrix = [
        ['U', 'A', 'I', 'O', 'U'], # Receiving relations
        ['A', 'U', 'E', 'I', 'O'], # Milling relations
        ['I', 'E', 'U', 'A', 'U'], # Press relations
        ['O', 'I', 'A', 'U', 'A'], # Assembly relations
        ['U', 'O', 'U', 'A', 'U']  # Shipping relations
    ]

    facility_width = 4

    # Run ALDEP
    aldep = ALDEP(departments, areas, rel_matrix, facility_width)

    # Generate Sequence
    seq = aldep.generate_sequence(mdp_letter='I')
    print("Placement Sequence:", seq)

    # Place Departments (Sweep Method)
    aldep.place_departments(seq)

    # Calculate Score
    score = aldep.calculate_layout_score()
    print("Layout Score:", score)

    # Visualize
    aldep.plot_layout(score)